import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding logs...");

  // Get the first organization (if exists)
  const organization = await prisma.organization.findFirst();

  const sampleLogs = [
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T10:30:00Z"),
      clientIp: "192.168.1.100",
      clientPort: 54321,
      host: "example.com",
      method: "POST",
      requestUrl: "/api/users/delete",
      rule: "SQL Injection Attack",
      ruleId: "942100",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "256",
        Accept: "application/json",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "example.com",
        "X-Forwarded-For": "192.168.1.100",
        Cookie: "session=abc123",
      },
      message: "SQL Injection detected in POST parameter",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 9,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "WARNING",
      timestamp: new Date("2025-12-15T10:31:15Z"),
      clientIp: "10.0.0.50",
      clientPort: 49152,
      host: "example.com",
      method: "GET",
      requestUrl: "/admin/dashboard",
      rule: "Suspicious User Agent",
      ruleId: "913100",
      userAgent: "curl/7.68.0",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "*/*",
        "User-Agent": "curl/7.68.0",
        Host: "example.com",
        "X-Real-Ip": "10.0.0.50",
      },
      message: "Suspicious user agent detected",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "1234",
        "X-Content-Type-Options": "nosniff",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 5,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T10:32:30Z"),
      clientIp: "203.0.113.45",
      clientPort: 45678,
      host: "api.example.com",
      method: "PUT",
      requestUrl: "/api/v1/users/123",
      rule: "Path Traversal Attack",
      ruleId: "930100",
      userAgent:
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "PUT",
        "Content-Type": "application/json",
        Authorization: "Bearer invalid_token",
        "User-Agent":
          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)",
        Host: "api.example.com",
        "X-Forwarded-For": "203.0.113.45",
      },
      message: "Path traversal attempt detected: ../etc/passwd",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "X-RateLimit-Remaining": "0",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 7,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "NOTICE",
      timestamp: new Date("2025-12-15T10:33:45Z"),
      clientIp: "172.16.0.20",
      clientPort: 32768,
      host: "example.com",
      method: "GET",
      requestUrl: "/wp-admin/install.php",
      rule: "Common Web Application Attack",
      ruleId: "913101",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "example.com",
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate",
        Connection: "keep-alive",
      },
      message: "Attempt to access WordPress admin installation page",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "5678",
        "X-Content-Type-Options": "nosniff",
        Status: "404 Not Found",
      },
      responseCode: 404,
      maturity: 3,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T10:35:00Z"),
      clientIp: "198.51.100.75",
      clientPort: 12345,
      host: "example.com",
      method: "POST",
      requestUrl: "/login",
      rule: "XSS Attack",
      ruleId: "941100",
      userAgent:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/x-www-form-urlencoded",
        "Content-Length": "128",
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        Host: "example.com",
        Origin: "https://malicious-site.com",
        Referer: "https://malicious-site.com",
        "X-Forwarded-For": "198.51.100.75",
      },
      message: "XSS attack detected in POST parameter: username",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "X-XSS-Protection": "1; mode=block",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 8,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "INFO",
      timestamp: new Date("2025-12-15T10:36:15Z"),
      clientIp: "192.168.1.200",
      clientPort: 54321,
      host: "example.com",
      method: "GET",
      requestUrl: "/api/health",
      rule: "Normal Request",
      ruleId: null,
      userAgent: "HealthCheck/1.0",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "application/json",
        "User-Agent": "HealthCheck/1.0",
        Host: "example.com",
      },
      message: "Normal health check request",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "45",
        "Cache-Control": "no-cache",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 0,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T10:37:30Z"),
      clientIp: "203.0.113.100",
      clientPort: 49152,
      host: "api.example.com",
      method: "DELETE",
      requestUrl: "/api/v1/users/999",
      rule: "Unauthorized Access Attempt",
      ruleId: "949110",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "DELETE",
        "Content-Type": "application/json",
        Authorization: "Bearer expired_token",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "api.example.com",
        "X-Requested-With": "XMLHttpRequest",
      },
      message: "Unauthorized DELETE request to user resource",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "WWW-Authenticate": "Bearer",
        "X-Content-Type-Options": "nosniff",
        Status: "401 Unauthorized",
      },
      responseCode: 401,
      maturity: 6,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "WARNING",
      timestamp: new Date("2025-12-15T10:38:45Z"),
      clientIp: "10.0.0.100",
      clientPort: 32768,
      host: "example.com",
      method: "POST",
      requestUrl: "/contact",
      rule: "Suspicious Request Pattern",
      ruleId: "913102",
      userAgent:
        "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/x-www-form-urlencoded",
        "Content-Length": "512",
        "User-Agent":
          "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15",
        Host: "example.com",
        Origin: "https://example.com",
        Referer: "https://example.com/contact",
        "X-Forwarded-For": "10.0.0.100",
      },
      message: "Unusual request pattern detected",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "2345",
        "X-Content-Type-Options": "nosniff",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 4,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T10:40:00Z"),
      clientIp: "185.220.101.50",
      clientPort: 45678,
      host: "example.com",
      method: "POST",
      requestUrl: "/api/upload",
      rule: "File Upload Attack",
      ruleId: "950100",
      userAgent: "python-requests/2.28.1",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "multipart/form-data",
        "Content-Length": "1048576",
        "User-Agent": "python-requests/2.28.1",
        Host: "example.com",
        "X-Forwarded-For": "185.220.101.50",
      },
      message: "Malicious file upload attempt: shell.php detected",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 9,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "NOTICE",
      timestamp: new Date("2025-12-15T10:41:15Z"),
      clientIp: "172.16.0.50",
      clientPort: 49152,
      host: "example.com",
      method: "GET",
      requestUrl: "/.env",
      rule: "Information Disclosure",
      ruleId: "950120",
      userAgent: "Mozilla/5.0 (compatible; Googlebot/2.1)",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "*/*",
        "User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1)",
        Host: "example.com",
      },
      message: "Attempt to access sensitive configuration file",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        Status: "404 Not Found",
      },
      responseCode: 404,
      maturity: 4,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T10:42:30Z"),
      clientIp: "198.51.100.200",
      clientPort: 54321,
      host: "api.example.com",
      method: "POST",
      requestUrl: "/api/auth/login",
      rule: "Brute Force Attack",
      ruleId: "949110",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "64",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "api.example.com",
        "X-Forwarded-For": "198.51.100.200",
      },
      message: "Multiple failed login attempts from same IP",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-RateLimit-Remaining": "0",
        "X-RateLimit-Reset": "1734265350",
        "X-Content-Type-Options": "nosniff",
        Status: "429 Too Many Requests",
      },
      responseCode: 429,
      maturity: 7,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "WARNING",
      timestamp: new Date("2025-12-15T10:43:45Z"),
      clientIp: "10.0.0.150",
      clientPort: 32768,
      host: "example.com",
      method: "GET",
      requestUrl: "/phpmyadmin/index.php",
      rule: "Common Web Application Attack",
      ruleId: "913101",
      userAgent:
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "text/html,application/xhtml+xml",
        "User-Agent":
          "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0",
        Host: "example.com",
        "Accept-Language": "en-US,en;q=0.9",
      },
      message: "Attempt to access phpMyAdmin interface",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        Status: "404 Not Found",
      },
      responseCode: 404,
      maturity: 3,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T10:45:00Z"),
      clientIp: "203.0.113.200",
      clientPort: 12345,
      host: "example.com",
      method: "POST",
      requestUrl: "/api/orders",
      rule: "Remote Code Execution",
      ruleId: "932100",
      userAgent: "PostmanRuntime/7.29.0",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "512",
        "User-Agent": "PostmanRuntime/7.29.0",
        Host: "example.com",
        Authorization: "Bearer valid_token",
        "X-Forwarded-For": "203.0.113.200",
      },
      message: "Remote code execution attempt detected in JSON payload",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 9,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "INFO",
      timestamp: new Date("2025-12-15T10:46:15Z"),
      clientIp: "192.168.1.50",
      clientPort: 49152,
      host: "example.com",
      method: "GET",
      requestUrl: "/api/products",
      rule: "Normal Request",
      ruleId: null,
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "application/json",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "example.com",
        "Accept-Language": "en-US,en;q=0.9",
      },
      message: "Normal API request",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "2048",
        "Cache-Control": "public, max-age=3600",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 0,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T10:47:30Z"),
      clientIp: "185.220.101.100",
      clientPort: 45678,
      host: "api.example.com",
      method: "PATCH",
      requestUrl: "/api/v1/users/1",
      rule: "Insecure Direct Object Reference",
      ruleId: "950110",
      userAgent: "curl/7.79.1",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "PATCH",
        "Content-Type": "application/json",
        "Content-Length": "256",
        "User-Agent": "curl/7.79.1",
        Host: "api.example.com",
        Authorization: "Bearer token_with_insufficient_permissions",
      },
      message: "Unauthorized access attempt to user resource",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "WWW-Authenticate": "Bearer",
        "X-Content-Type-Options": "nosniff",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 6,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "NOTICE",
      timestamp: new Date("2025-12-15T10:48:45Z"),
      clientIp: "172.16.0.100",
      clientPort: 32768,
      host: "example.com",
      method: "GET",
      requestUrl: "/admin/config.php",
      rule: "Information Disclosure",
      ruleId: "950120",
      userAgent:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "text/html,application/xhtml+xml",
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        Host: "example.com",
        "Accept-Language": "en-US,en;q=0.9",
      },
      message: "Attempt to access configuration file",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        Status: "404 Not Found",
      },
      responseCode: 404,
      maturity: 4,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T10:50:00Z"),
      clientIp: "198.51.100.150",
      clientPort: 54321,
      host: "example.com",
      method: "POST",
      requestUrl: "/api/execute",
      rule: "Command Injection",
      ruleId: "932150",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "128",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "example.com",
        "X-Forwarded-For": "198.51.100.150",
      },
      message: "Command injection attempt: ; rm -rf / detected",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 9,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "WARNING",
      timestamp: new Date("2025-12-15T10:51:15Z"),
      clientIp: "10.0.0.200",
      clientPort: 49152,
      host: "example.com",
      method: "GET",
      requestUrl: "/.git/config",
      rule: "Information Disclosure",
      ruleId: "950120",
      userAgent: "git/2.30.0",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "*/*",
        "User-Agent": "git/2.30.0",
        Host: "example.com",
      },
      message: "Attempt to access Git configuration",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/plain",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        Status: "404 Not Found",
      },
      responseCode: 404,
      maturity: 4,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T10:52:30Z"),
      clientIp: "203.0.113.150",
      clientPort: 45678,
      host: "api.example.com",
      method: "POST",
      requestUrl: "/api/payment/process",
      rule: "Credit Card Skimming",
      ruleId: "942200",
      userAgent:
        "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "512",
        "User-Agent":
          "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15",
        Host: "api.example.com",
        Origin: "https://phishing-site.com",
        Referer: "https://phishing-site.com/payment",
      },
      message: "Suspicious payment processing request from external origin",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 8,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "INFO",
      timestamp: new Date("2025-12-15T10:53:45Z"),
      clientIp: "192.168.1.150",
      clientPort: 32768,
      host: "example.com",
      method: "GET",
      requestUrl: "/dashboard",
      rule: "Normal Request",
      ruleId: null,
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "text/html,application/xhtml+xml",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "example.com",
        Cookie: "session=valid_session_token",
        "Accept-Language": "en-US,en;q=0.9",
      },
      message: "Normal dashboard access",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/html",
        "Content-Length": "8192",
        "Set-Cookie": "session=valid_session_token; HttpOnly; Secure",
        "X-Content-Type-Options": "nosniff",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 0,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T10:55:00Z"),
      clientIp: "185.220.101.200",
      clientPort: 12345,
      host: "example.com",
      method: "POST",
      requestUrl: "/api/admin/users",
      rule: "Privilege Escalation",
      ruleId: "949110",
      userAgent: "python-requests/2.28.1",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "256",
        "User-Agent": "python-requests/2.28.1",
        Host: "example.com",
        Authorization: "Bearer user_token_not_admin",
        "X-Forwarded-For": "185.220.101.200",
      },
      message: "Non-admin user attempting admin operation",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "WWW-Authenticate": "Bearer",
        "X-Content-Type-Options": "nosniff",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 7,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "NOTICE",
      timestamp: new Date("2025-12-15T10:56:15Z"),
      clientIp: "172.16.0.150",
      clientPort: 49152,
      host: "example.com",
      method: "GET",
      requestUrl: "/backup/database.sql",
      rule: "Information Disclosure",
      ruleId: "950120",
      userAgent: "wget/1.21.2",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "*/*",
        "User-Agent": "wget/1.21.2",
        Host: "example.com",
      },
      message: "Attempt to access backup file",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/plain",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        Status: "404 Not Found",
      },
      responseCode: 404,
      maturity: 4,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T10:57:30Z"),
      clientIp: "198.51.100.250",
      clientPort: 54321,
      host: "api.example.com",
      method: "PUT",
      requestUrl: "/api/v1/settings",
      rule: "XML External Entity",
      ruleId: "933100",
      userAgent:
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "PUT",
        "Content-Type": "application/xml",
        "Content-Length": "1024",
        "User-Agent":
          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)",
        Host: "api.example.com",
        Authorization: "Bearer valid_token",
      },
      message: "XXE attack detected in XML payload",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 8,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "WARNING",
      timestamp: new Date("2025-12-15T10:58:45Z"),
      clientIp: "10.0.0.250",
      clientPort: 32768,
      host: "example.com",
      method: "GET",
      requestUrl: "/robots.txt",
      rule: "Normal Request",
      ruleId: null,
      userAgent: "Googlebot/2.1",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "*/*",
        "User-Agent": "Googlebot/2.1",
        Host: "example.com",
      },
      message: "Normal robots.txt request",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "text/plain",
        "Content-Length": "256",
        "Cache-Control": "public, max-age=86400",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 0,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "CRITICAL",
      timestamp: new Date("2025-12-15T11:00:00Z"),
      clientIp: "203.0.113.250",
      clientPort: 45678,
      host: "example.com",
      method: "POST",
      requestUrl: "/api/auth/reset-password",
      rule: "Account Takeover",
      ruleId: "942300",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "128",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        Host: "example.com",
        "X-Forwarded-For": "203.0.113.250",
      },
      message: "Suspicious password reset attempt",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 9,
    },
    {
      organizationId: organization?.id || null,
      action: "warning",
      severity: "INFO",
      timestamp: new Date("2025-12-15T11:01:15Z"),
      clientIp: "192.168.1.250",
      clientPort: 49152,
      host: "example.com",
      method: "GET",
      requestUrl: "/sitemap.xml",
      rule: "Normal Request",
      ruleId: null,
      userAgent: "Mozilla/5.0 (compatible; bingbot/2.0)",
      headers: {
        "HTTP-Method": "HTTP/1.1",
        Method: "GET",
        Accept: "*/*",
        "User-Agent": "Mozilla/5.0 (compatible; bingbot/2.0)",
        Host: "example.com",
      },
      message: "Normal sitemap request",
      httpMethod: "HTTP/1.1",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/xml",
        "Content-Length": "4096",
        "Cache-Control": "public, max-age=3600",
        Status: "200 OK",
      },
      responseCode: 200,
      maturity: 0,
    },
    {
      organizationId: organization?.id || null,
      action: "blocked",
      severity: "ERROR",
      timestamp: new Date("2025-12-15T11:02:30Z"),
      clientIp: "185.220.101.250",
      clientPort: 12345,
      host: "api.example.com",
      method: "POST",
      requestUrl: "/api/webhook",
      rule: "Server-Side Request Forgery",
      ruleId: "932200",
      userAgent: "curl/7.79.1",
      headers: {
        "HTTP-Method": "HTTP/2",
        Method: "POST",
        "Content-Type": "application/json",
        "Content-Length": "512",
        "User-Agent": "curl/7.79.1",
        Host: "api.example.com",
        "X-Webhook-Signature": "invalid_signature",
      },
      message: "SSRF attack detected: internal network access attempt",
      httpMethod: "HTTP/2",
      responseHeader: {
        Server: "nginx/1.18.0",
        "Content-Type": "application/json",
        "Content-Length": "0",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        Status: "403 Forbidden",
      },
      responseCode: 403,
      maturity: 8,
    },
  ];

  for (const log of sampleLogs) {
    await prisma.log.create({
      data: log,
    });
  }

  console.log(`✅ Seeded ${sampleLogs.length} log entries`);
}

main()
  .catch((e) => {
    console.error("❌ Error seeding logs:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
